#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
A Nessus Helper
:copyright: (c) 2016 Rocket Internet SE
:license: MIT, see LICENSE for more details.
"""

__author__ = "Levon Kayan"
__email__ = "levon.kayan@rocket-internet.de"

# own imports
from controller import Controller

# system imports
import sys


if __name__ == '__main__':
    try:
        ctrl = Controller()
        ctrl.start()
        ctrl.end()
    except KeyboardInterrupt:
        sys.stderr.write('\b\b[!] WARNING: Aborted by user\n')
        raise SystemExit


# EOF
